
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 04 21:36:18 COT 2022
//----------------------------------------------------

package Compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 19;
  public static final int Coma = 67;
  public static final int Llave_c = 27;
  public static final int Op_booleano = 22;
  public static final int Declara = 70;
  public static final int Unsigned = 36;
  public static final int Llave_a = 26;
  public static final int If = 6;
  public static final int Namespace = 35;
  public static final int Void = 37;
  public static final int T_dato = 4;
  public static final int Op_alcance = 54;
  public static final int Static = 41;
  public static final int Define = 60;
  public static final int Default = 48;
  public static final int Sizeof = 64;
  public static final int Else = 7;
  public static final int Cout = 58;
  public static final int Enum = 47;
  public static final int Break = 39;
  public static final int Goto = 52;
  public static final int Corchete_c = 29;
  public static final int Extern = 55;
  public static final int Corchete_a = 28;
  public static final int Union = 49;
  public static final int Volatile = 51;
  public static final int Punto = 32;
  public static final int Parent_c = 24;
  public static final int Return = 53;
  public static final int Parent_a = 23;
  public static final int While = 9;
  public static final int Division = 17;
  public static final int Int = 11;
  public static final int Directiva = 45;
  public static final int Cadena = 5;
  public static final int Ampersand = 68;
  public static final int For = 10;
  public static final int Std = 50;
  public static final int EOF = 0;
  public static final int P_coma = 31;
  public static final int Printf = 25;
  public static final int error = 1;
  public static final int Switch = 38;
  public static final int Linea = 2;
  public static final int Char = 12;
  public static final int Op_atribucion = 20;
  public static final int ERROR = 66;
  public static final int Signed = 57;
  public static final int Do = 8;
  public static final int Continue = 46;
  public static final int Case = 62;
  public static final int Op_logico = 18;
  public static final int Register = 63;
  public static final int Short = 43;
  public static final int Dos_puntos = 69;
  public static final int Scanf = 42;
  public static final int Const = 44;
  public static final int Identificador = 33;
  public static final int Using = 65;
  public static final int Struct = 59;
  public static final int Cin = 40;
  public static final int Resta = 15;
  public static final int Typedef = 61;
  public static final int Multiplicacion = 16;
  public static final int Op_incremento = 21;
  public static final int Numero = 34;
  public static final int Suma = 14;
  public static final int Include = 56;
  public static final int Main = 30;
  public static final int Igual = 13;
  public static final int Comillas = 3;
}

